total_reallocation_number = 100

[layer_0]
q_proj = 0
v_proj = 0
residual_1 = 0
residual_2 = 0
shortcut_sa = 0

[layer_1]
q_proj = 0
v_proj = 95
residual_1 = 0
residual_2 = 0
shortcut_sa = 6
shortcut_ffn = 0

[layer_2]
q_proj = 0
v_proj = 99
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_3]
q_proj = 0
v_proj = 96
residual_1 = 0
residual_2 = 1
shortcut_sa = 0
shortcut_ffn = 0

[layer_4]
q_proj = 0
v_proj = 91
residual_1 = 0
residual_2 = 2
shortcut_sa = 86
shortcut_ffn = 0

[layer_5]
q_proj = 0
v_proj = 100
residual_1 = 66
residual_2 = 88
shortcut_sa = 0
shortcut_ffn = 0

[layer_6]
q_proj = 0
v_proj = 99
residual_1 = 2
residual_2 = 16
shortcut_sa = 0
shortcut_ffn = 81

[layer_7]
q_proj = 0
v_proj = 97
residual_1 = 3
residual_2 = 72
shortcut_sa = 61
shortcut_ffn = 0

[layer_8]
q_proj = 0
v_proj = 99
residual_1 = 1
residual_2 = 70
shortcut_sa = 88
shortcut_ffn = 0

[layer_9]
q_proj = 0
v_proj = 100
residual_1 = 0
residual_2 = 84
shortcut_sa = 86
shortcut_ffn = 36

[layer_10]
q_proj = 94
v_proj = 100
residual_1 = 0
residual_2 = 0
shortcut_sa = 86
shortcut_ffn = 0

[layer_11]
q_proj = 0
v_proj = 100
residual_1 = 0
residual_2 = 4
shortcut_sa = 93
shortcut_ffn = 0

[layer_12]
q_proj = 0
v_proj = 100
residual_1 = 1
residual_2 = 0
shortcut_sa = 4
shortcut_ffn = 0

[layer_13]
q_proj = 0
v_proj = 100
residual_1 = 0
residual_2 = 1
shortcut_sa = 0
shortcut_ffn = 1

[layer_14]
q_proj = 0
v_proj = 100
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_15]
q_proj = 0
v_proj = 100
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_16]
q_proj = 0
v_proj = 97
residual_1 = 1
residual_2 = 0
shortcut_sa = 99
shortcut_ffn = 0

[layer_17]
q_proj = 0
v_proj = 77
residual_1 = 1
residual_2 = 0
shortcut_sa = 97
shortcut_ffn = 15

[layer_18]
q_proj = 0
v_proj = 76
residual_1 = 1
residual_2 = 1
shortcut_sa = 0
shortcut_ffn = 0

[layer_19]
q_proj = 0
v_proj = 97
residual_1 = 1
residual_2 = 89
shortcut_sa = 43
shortcut_ffn = 5

[layer_20]
q_proj = 0
v_proj = 98
residual_1 = 5
residual_2 = 9
shortcut_sa = 37
shortcut_ffn = 3

[layer_21]
q_proj = 0
v_proj = 25
residual_1 = 9
residual_2 = 8
shortcut_sa = 8
shortcut_ffn = 4

[layer_22]
q_proj = 0
v_proj = 16
residual_1 = 7
residual_2 = 5
shortcut_sa = 18
shortcut_ffn = 5

[layer_23]
q_proj = 0
v_proj = 25
residual_1 = 1
residual_2 = 4
shortcut_sa = 0
shortcut_ffn = 4
