total_reallocation_number = 100

[layer_0]
q_proj = 0
v_proj = 30
residual_1 = 46
residual_2 = 0
shortcut_sa = 0

[layer_1]
q_proj = 0
v_proj = 97
residual_1 = 0
residual_2 = 0
shortcut_sa = 1
shortcut_ffn = 0

[layer_2]
q_proj = 0
v_proj = 93
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_3]
q_proj = 0
v_proj = 93
residual_1 = 0
residual_2 = 0
shortcut_sa = 11
shortcut_ffn = 0

[layer_4]
q_proj = 0
v_proj = 93
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_5]
q_proj = 0
v_proj = 93
residual_1 = 0
residual_2 = 13
shortcut_sa = 10
shortcut_ffn = 69

[layer_6]
q_proj = 0
v_proj = 97
residual_1 = 1
residual_2 = 0
shortcut_sa = 27
shortcut_ffn = 1

[layer_7]
q_proj = 0
v_proj = 97
residual_1 = 0
residual_2 = 1
shortcut_sa = 25
shortcut_ffn = 0

[layer_8]
q_proj = 0
v_proj = 97
residual_1 = 0
residual_2 = 0
shortcut_sa = 51
shortcut_ffn = 34

[layer_9]
q_proj = 0
v_proj = 100
residual_1 = 88
residual_2 = 82
shortcut_sa = 84
shortcut_ffn = 77

[layer_10]
q_proj = 90
v_proj = 100
residual_1 = 0
residual_2 = 17
shortcut_sa = 0
shortcut_ffn = 0

[layer_11]
q_proj = 0
v_proj = 100
residual_1 = 0
residual_2 = 45
shortcut_sa = 0
shortcut_ffn = 1

[layer_12]
q_proj = 36
v_proj = 100
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_13]
q_proj = 0
v_proj = 100
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_14]
q_proj = 0
v_proj = 100
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_15]
q_proj = 0
v_proj = 99
residual_1 = 0
residual_2 = 0
shortcut_sa = 99
shortcut_ffn = 3

[layer_16]
q_proj = 0
v_proj = 85
residual_1 = 0
residual_2 = 0
shortcut_sa = 2
shortcut_ffn = 0

[layer_17]
q_proj = 0
v_proj = 39
residual_1 = 0
residual_2 = 0
shortcut_sa = 84
shortcut_ffn = 0

[layer_18]
q_proj = 0
v_proj = 73
residual_1 = 2
residual_2 = 6
shortcut_sa = 70
shortcut_ffn = 0

[layer_19]
q_proj = 0
v_proj = 56
residual_1 = 28
residual_2 = 36
shortcut_sa = 99
shortcut_ffn = 23

[layer_20]
q_proj = 0
v_proj = 99
residual_1 = 3
residual_2 = 11
shortcut_sa = 9
shortcut_ffn = 74

[layer_21]
q_proj = 0
v_proj = 67
residual_1 = 9
residual_2 = 6
shortcut_sa = 18
shortcut_ffn = 86

[layer_22]
q_proj = 0
v_proj = 98
residual_1 = 8
residual_2 = 5
shortcut_sa = 7
shortcut_ffn = 9

[layer_23]
q_proj = 0
v_proj = 85
residual_1 = 1
residual_2 = 0
shortcut_sa = 1
shortcut_ffn = 0
