total_reallocation_number = 100

[layer_0]
q_proj = 0
v_proj = 0
residual_1 = 62
residual_2 = 64
shortcut_sa = 0

[layer_1]
q_proj = 0
v_proj = 67
residual_1 = 0
residual_2 = 1
shortcut_sa = 59
shortcut_ffn = 0

[layer_2]
q_proj = 0
v_proj = 84
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 1

[layer_3]
q_proj = 0
v_proj = 6
residual_1 = 0
residual_2 = 1
shortcut_sa = 0
shortcut_ffn = 0

[layer_4]
q_proj = 0
v_proj = 6
residual_1 = 0
residual_2 = 9
shortcut_sa = 95
shortcut_ffn = 5

[layer_5]
q_proj = 0
v_proj = 97
residual_1 = 93
residual_2 = 71
shortcut_sa = 0
shortcut_ffn = 0

[layer_6]
q_proj = 0
v_proj = 64
residual_1 = 1
residual_2 = 1
shortcut_sa = 88
shortcut_ffn = 92

[layer_7]
q_proj = 0
v_proj = 90
residual_1 = 0
residual_2 = 82
shortcut_sa = 90
shortcut_ffn = 15

[layer_8]
q_proj = 0
v_proj = 97
residual_1 = 17
residual_2 = 55
shortcut_sa = 95
shortcut_ffn = 1

[layer_9]
q_proj = 0
v_proj = 96
residual_1 = 2
residual_2 = 90
shortcut_sa = 97
shortcut_ffn = 22

[layer_10]
q_proj = 92
v_proj = 93
residual_1 = 0
residual_2 = 84
shortcut_sa = 93
shortcut_ffn = 0

[layer_11]
q_proj = 0
v_proj = 100
residual_1 = 0
residual_2 = 6
shortcut_sa = 92
shortcut_ffn = 0

[layer_12]
q_proj = 0
v_proj = 100
residual_1 = 2
residual_2 = 0
shortcut_sa = 7
shortcut_ffn = 0

[layer_13]
q_proj = 0
v_proj = 2
residual_1 = 0
residual_2 = 3
shortcut_sa = 4
shortcut_ffn = 1

[layer_14]
q_proj = 0
v_proj = 80
residual_1 = 0
residual_2 = 0
shortcut_sa = 2
shortcut_ffn = 0

[layer_15]
q_proj = 0
v_proj = 8
residual_1 = 1
residual_2 = 29
shortcut_sa = 5
shortcut_ffn = 0

[layer_16]
q_proj = 0
v_proj = 46
residual_1 = 1
residual_2 = 2
shortcut_sa = 100
shortcut_ffn = 1

[layer_17]
q_proj = 0
v_proj = 19
residual_1 = 91
residual_2 = 3
shortcut_sa = 99
shortcut_ffn = 99

[layer_18]
q_proj = 0
v_proj = 2
residual_1 = 76
residual_2 = 1
shortcut_sa = 2
shortcut_ffn = 2

[layer_19]
q_proj = 0
v_proj = 19
residual_1 = 2
residual_2 = 86
shortcut_sa = 47
shortcut_ffn = 84

[layer_20]
q_proj = 0
v_proj = 6
residual_1 = 7
residual_2 = 43
shortcut_sa = 32
shortcut_ffn = 3

[layer_21]
q_proj = 0
v_proj = 14
residual_1 = 10
residual_2 = 10
shortcut_sa = 11
shortcut_ffn = 4

[layer_22]
q_proj = 0
v_proj = 6
residual_1 = 10
residual_2 = 4
shortcut_sa = 17
shortcut_ffn = 4

[layer_23]
q_proj = 0
v_proj = 6
residual_1 = 1
residual_2 = 5
shortcut_sa = 4
shortcut_ffn = 1
