total_reallocation_number = 100

[layer_0]
q_proj = 0
v_proj = 0

[layer_1]
q_proj = 0
v_proj = 98

[layer_2]
q_proj = 0
v_proj = 2

[layer_3]
q_proj = 0
v_proj = 0

[layer_4]
q_proj = 0
v_proj = 1

[layer_5]
q_proj = 0
v_proj = 2

[layer_6]
q_proj = 0
v_proj = 0

[layer_7]
q_proj = 0
v_proj = 0

[layer_8]
q_proj = 0
v_proj = 5

[layer_9]
q_proj = 0
v_proj = 5

[layer_10]
q_proj = 0
v_proj = 80

[layer_11]
q_proj = 0
v_proj = 100

[layer_12]
q_proj = 0
v_proj = 97

[layer_13]
q_proj = 0
v_proj = 100

[layer_14]
q_proj = 0
v_proj = 100

[layer_15]
q_proj = 0
v_proj = 100

[layer_16]
q_proj = 0
v_proj = 60

[layer_17]
q_proj = 0
v_proj = 71

[layer_18]
q_proj = 0
v_proj = 97

[layer_19]
q_proj = 0
v_proj = 99

[layer_20]
q_proj = 0
v_proj = 99

[layer_21]
q_proj = 0
v_proj = 64

[layer_22]
q_proj = 0
v_proj = 6

[layer_23]
q_proj = 0
v_proj = 14
