total_reallocation_number = 100

[layer_0]
q_proj = 0
v_proj = 0
residual_1 = 0
residual_2 = 1
shortcut_sa = 0

[layer_1]
q_proj = 0
v_proj = 2
residual_1 = 0
residual_2 = 1
shortcut_sa = 3
shortcut_ffn = 2

[layer_2]
q_proj = 0
v_proj = 75
residual_1 = 0
residual_2 = 1
shortcut_sa = 5
shortcut_ffn = 0

[layer_3]
q_proj = 0
v_proj = 4
residual_1 = 1
residual_2 = 1
shortcut_sa = 1
shortcut_ffn = 0

[layer_4]
q_proj = 0
v_proj = 50
residual_1 = 2
residual_2 = 65
shortcut_sa = 5
shortcut_ffn = 2

[layer_5]
q_proj = 0
v_proj = 59
residual_1 = 2
residual_2 = 3
shortcut_sa = 6
shortcut_ffn = 34

[layer_6]
q_proj = 0
v_proj = 90
residual_1 = 3
residual_2 = 3
shortcut_sa = 64
shortcut_ffn = 1

[layer_7]
q_proj = 0
v_proj = 62
residual_1 = 4
residual_2 = 11
shortcut_sa = 49
shortcut_ffn = 53

[layer_8]
q_proj = 0
v_proj = 81
residual_1 = 2
residual_2 = 7
shortcut_sa = 63
shortcut_ffn = 13

[layer_9]
q_proj = 0
v_proj = 88
residual_1 = 2
residual_2 = 67
shortcut_sa = 80
shortcut_ffn = 5

[layer_10]
q_proj = 66
v_proj = 100
residual_1 = 20
residual_2 = 3
shortcut_sa = 27
shortcut_ffn = 62

[layer_11]
q_proj = 0
v_proj = 92
residual_1 = 2
residual_2 = 5
shortcut_sa = 1
shortcut_ffn = 1

[layer_12]
q_proj = 2
v_proj = 53
residual_1 = 0
residual_2 = 0
shortcut_sa = 7
shortcut_ffn = 2

[layer_13]
q_proj = 0
v_proj = 100
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_14]
q_proj = 0
v_proj = 38
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_15]
q_proj = 0
v_proj = 22
residual_1 = 0
residual_2 = 0
shortcut_sa = 3
shortcut_ffn = 88

[layer_16]
q_proj = 0
v_proj = 23
residual_1 = 92
residual_2 = 0
shortcut_sa = 3
shortcut_ffn = 0

[layer_17]
q_proj = 0
v_proj = 29
residual_1 = 96
residual_2 = 0
shortcut_sa = 98
shortcut_ffn = 99

[layer_18]
q_proj = 0
v_proj = 51
residual_1 = 0
residual_2 = 83
shortcut_sa = 99
shortcut_ffn = 99

[layer_19]
q_proj = 0
v_proj = 25
residual_1 = 48
residual_2 = 47
shortcut_sa = 97
shortcut_ffn = 97

[layer_20]
q_proj = 0
v_proj = 24
residual_1 = 20
residual_2 = 92
shortcut_sa = 95
shortcut_ffn = 50

[layer_21]
q_proj = 0
v_proj = 13
residual_1 = 93
residual_2 = 30
shortcut_sa = 70
shortcut_ffn = 79

[layer_22]
q_proj = 0
v_proj = 28
residual_1 = 29
residual_2 = 22
shortcut_sa = 36
shortcut_ffn = 33

[layer_23]
q_proj = 0
v_proj = 23
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 10
