total_reallocation_number = 100

[layer_0]
q_proj = 0
v_proj = 48
residual_1 = 0
residual_2 = 0
shortcut_sa = 0

[layer_1]
q_proj = 0
v_proj = 93
residual_1 = 3
residual_2 = 0
shortcut_sa = 49
shortcut_ffn = 1

[layer_2]
q_proj = 0
v_proj = 91
residual_1 = 0
residual_2 = 1
shortcut_sa = 64
shortcut_ffn = 0

[layer_3]
q_proj = 0
v_proj = 91
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_4]
q_proj = 0
v_proj = 96
residual_1 = 0
residual_2 = 54
shortcut_sa = 55
shortcut_ffn = 0

[layer_5]
q_proj = 0
v_proj = 94
residual_1 = 0
residual_2 = 69
shortcut_sa = 0
shortcut_ffn = 48

[layer_6]
q_proj = 0
v_proj = 100
residual_1 = 0
residual_2 = 0
shortcut_sa = 83
shortcut_ffn = 0

[layer_7]
q_proj = 0
v_proj = 92
residual_1 = 55
residual_2 = 79
shortcut_sa = 77
shortcut_ffn = 75

[layer_8]
q_proj = 0
v_proj = 96
residual_1 = 3
residual_2 = 0
shortcut_sa = 90
shortcut_ffn = 76

[layer_9]
q_proj = 0
v_proj = 100
residual_1 = 0
residual_2 = 57
shortcut_sa = 77
shortcut_ffn = 0

[layer_10]
q_proj = 93
v_proj = 100
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_11]
q_proj = 0
v_proj = 100
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_12]
q_proj = 27
v_proj = 100
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_13]
q_proj = 0
v_proj = 100
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_14]
q_proj = 0
v_proj = 99
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_15]
q_proj = 0
v_proj = 82
residual_1 = 0
residual_2 = 0
shortcut_sa = 1
shortcut_ffn = 9

[layer_16]
q_proj = 0
v_proj = 64
residual_1 = 1
residual_2 = 1
shortcut_sa = 0
shortcut_ffn = 0

[layer_17]
q_proj = 0
v_proj = 44
residual_1 = 1
residual_2 = 0
shortcut_sa = 42
shortcut_ffn = 1

[layer_18]
q_proj = 0
v_proj = 69
residual_1 = 0
residual_2 = 6
shortcut_sa = 2
shortcut_ffn = 75

[layer_19]
q_proj = 0
v_proj = 73
residual_1 = 5
residual_2 = 8
shortcut_sa = 97
shortcut_ffn = 5

[layer_20]
q_proj = 0
v_proj = 70
residual_1 = 12
residual_2 = 40
shortcut_sa = 18
shortcut_ffn = 56

[layer_21]
q_proj = 0
v_proj = 63
residual_1 = 20
residual_2 = 13
shortcut_sa = 28
shortcut_ffn = 20

[layer_22]
q_proj = 0
v_proj = 35
residual_1 = 8
residual_2 = 24
shortcut_sa = 9
shortcut_ffn = 10

[layer_23]
q_proj = 0
v_proj = 41
residual_1 = 0
residual_2 = 2
shortcut_sa = 8
shortcut_ffn = 1
