total_reallocation_number = 100

[layer_0]
q_proj = 0
v_proj = 1
residual_1 = 0
residual_2 = 0
shortcut_sa = 0

[layer_1]
q_proj = 0
v_proj = 78
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 1

[layer_2]
q_proj = 0
v_proj = 87
residual_1 = 0
residual_2 = 0
shortcut_sa = 1
shortcut_ffn = 0

[layer_3]
q_proj = 0
v_proj = 91
residual_1 = 0
residual_2 = 1
shortcut_sa = 4
shortcut_ffn = 1

[layer_4]
q_proj = 0
v_proj = 91
residual_1 = 0
residual_2 = 4
shortcut_sa = 50
shortcut_ffn = 0

[layer_5]
q_proj = 0
v_proj = 92
residual_1 = 0
residual_2 = 60
shortcut_sa = 15
shortcut_ffn = 2

[layer_6]
q_proj = 0
v_proj = 90
residual_1 = 25
residual_2 = 68
shortcut_sa = 67
shortcut_ffn = 1

[layer_7]
q_proj = 0
v_proj = 93
residual_1 = 54
residual_2 = 65
shortcut_sa = 66
shortcut_ffn = 3

[layer_8]
q_proj = 0
v_proj = 100
residual_1 = 1
residual_2 = 56
shortcut_sa = 66
shortcut_ffn = 3

[layer_9]
q_proj = 0
v_proj = 89
residual_1 = 3
residual_2 = 78
shortcut_sa = 78
shortcut_ffn = 6

[layer_10]
q_proj = 81
v_proj = 100
residual_1 = 40
residual_2 = 49
shortcut_sa = 74
shortcut_ffn = 34

[layer_11]
q_proj = 0
v_proj = 100
residual_1 = 0
residual_2 = 2
shortcut_sa = 31
shortcut_ffn = 0

[layer_12]
q_proj = 31
v_proj = 100
residual_1 = 0
residual_2 = 5
shortcut_sa = 0
shortcut_ffn = 0

[layer_13]
q_proj = 0
v_proj = 100
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_14]
q_proj = 0
v_proj = 93
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_15]
q_proj = 0
v_proj = 82
residual_1 = 0
residual_2 = 0
shortcut_sa = 2
shortcut_ffn = 0

[layer_16]
q_proj = 0
v_proj = 54
residual_1 = 0
residual_2 = 0
shortcut_sa = 98
shortcut_ffn = 0

[layer_17]
q_proj = 0
v_proj = 40
residual_1 = 6
residual_2 = 7
shortcut_sa = 99
shortcut_ffn = 0

[layer_18]
q_proj = 0
v_proj = 49
residual_1 = 0
residual_2 = 6
shortcut_sa = 96
shortcut_ffn = 7

[layer_19]
q_proj = 0
v_proj = 35
residual_1 = 6
residual_2 = 24
shortcut_sa = 73
shortcut_ffn = 5

[layer_20]
q_proj = 0
v_proj = 30
residual_1 = 10
residual_2 = 21
shortcut_sa = 52
shortcut_ffn = 63

[layer_21]
q_proj = 0
v_proj = 49
residual_1 = 21
residual_2 = 21
shortcut_sa = 29
shortcut_ffn = 39

[layer_22]
q_proj = 0
v_proj = 32
residual_1 = 22
residual_2 = 14
shortcut_sa = 22
shortcut_ffn = 23

[layer_23]
q_proj = 0
v_proj = 32
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0
