total_reallocation_number = 40

[layer_0]
q_proj = 0
v_proj = 0
residual_1 = 0
residual_2 = 0
shortcut_sa = 0

[layer_1]
q_proj = 0
v_proj = 10
residual_1 = 0
residual_2 = 0
shortcut_sa = 34
shortcut_ffn = 0

[layer_2]
q_proj = 0
v_proj = 33
residual_1 = 0
residual_2 = 0
shortcut_sa = 34
shortcut_ffn = 0

[layer_3]
q_proj = 0
v_proj = 19
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_4]
q_proj = 0
v_proj = 11
residual_1 = 28
residual_2 = 28
shortcut_sa = 34
shortcut_ffn = 2

[layer_5]
q_proj = 0
v_proj = 27
residual_1 = 3
residual_2 = 32
shortcut_sa = 33
shortcut_ffn = 0

[layer_6]
q_proj = 0
v_proj = 18
residual_1 = 23
residual_2 = 1
shortcut_sa = 33
shortcut_ffn = 0

[layer_7]
q_proj = 0
v_proj = 35
residual_1 = 1
residual_2 = 24
shortcut_sa = 34
shortcut_ffn = 34

[layer_8]
q_proj = 0
v_proj = 35
residual_1 = 0
residual_2 = 19
shortcut_sa = 35
shortcut_ffn = 22

[layer_9]
q_proj = 0
v_proj = 37
residual_1 = 10
residual_2 = 33
shortcut_sa = 34
shortcut_ffn = 0

[layer_10]
q_proj = 30
v_proj = 40
residual_1 = 0
residual_2 = 7
shortcut_sa = 0
shortcut_ffn = 11

[layer_11]
q_proj = 0
v_proj = 37
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_12]
q_proj = 0
v_proj = 33
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 1

[layer_13]
q_proj = 0
v_proj = 40
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_14]
q_proj = 0
v_proj = 9
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_15]
q_proj = 0
v_proj = 8
residual_1 = 2
residual_2 = 0
shortcut_sa = 3
shortcut_ffn = 39

[layer_16]
q_proj = 0
v_proj = 9
residual_1 = 25
residual_2 = 1
shortcut_sa = 1
shortcut_ffn = 0

[layer_17]
q_proj = 0
v_proj = 8
residual_1 = 40
residual_2 = 0
shortcut_sa = 40
shortcut_ffn = 40

[layer_18]
q_proj = 0
v_proj = 11
residual_1 = 0
residual_2 = 7
shortcut_sa = 33
shortcut_ffn = 39

[layer_19]
q_proj = 0
v_proj = 9
residual_1 = 6
residual_2 = 6
shortcut_sa = 17
shortcut_ffn = 23

[layer_20]
q_proj = 0
v_proj = 7
residual_1 = 6
residual_2 = 11
shortcut_sa = 9
shortcut_ffn = 6

[layer_21]
q_proj = 0
v_proj = 5
residual_1 = 4
residual_2 = 4
shortcut_sa = 7
shortcut_ffn = 6

[layer_22]
q_proj = 0
v_proj = 4
residual_1 = 4
residual_2 = 7
shortcut_sa = 16
shortcut_ffn = 4

[layer_23]
q_proj = 0
v_proj = 5
residual_1 = 0
residual_2 = 3
shortcut_sa = 0
shortcut_ffn = 1
