total_reallocation_number = 20

[layer_0]
q_proj = 0
v_proj = 0
residual_1 = 0
residual_2 = 0
shortcut_sa = 0

[layer_1]
q_proj = 0
v_proj = 7
residual_1 = 0
residual_2 = 0
shortcut_sa = 1
shortcut_ffn = 0

[layer_2]
q_proj = 0
v_proj = 9
residual_1 = 0
residual_2 = 0
shortcut_sa = 17
shortcut_ffn = 0

[layer_3]
q_proj = 0
v_proj = 0
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_4]
q_proj = 0
v_proj = 11
residual_1 = 1
residual_2 = 15
shortcut_sa = 0
shortcut_ffn = 1

[layer_5]
q_proj = 0
v_proj = 17
residual_1 = 2
residual_2 = 14
shortcut_sa = 1
shortcut_ffn = 0

[layer_6]
q_proj = 0
v_proj = 17
residual_1 = 1
residual_2 = 0
shortcut_sa = 13
shortcut_ffn = 0

[layer_7]
q_proj = 0
v_proj = 12
residual_1 = 4
residual_2 = 12
shortcut_sa = 12
shortcut_ffn = 2

[layer_8]
q_proj = 0
v_proj = 8
residual_1 = 1
residual_2 = 0
shortcut_sa = 12
shortcut_ffn = 1

[layer_9]
q_proj = 0
v_proj = 18
residual_1 = 1
residual_2 = 11
shortcut_sa = 16
shortcut_ffn = 0

[layer_10]
q_proj = 10
v_proj = 20
residual_1 = 5
residual_2 = 15
shortcut_sa = 1
shortcut_ffn = 2

[layer_11]
q_proj = 0
v_proj = 16
residual_1 = 1
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_12]
q_proj = 0
v_proj = 16
residual_1 = 0
residual_2 = 0
shortcut_sa = 4
shortcut_ffn = 2

[layer_13]
q_proj = 0
v_proj = 20
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_14]
q_proj = 0
v_proj = 5
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_15]
q_proj = 0
v_proj = 6
residual_1 = 0
residual_2 = 0
shortcut_sa = 1
shortcut_ffn = 20

[layer_16]
q_proj = 0
v_proj = 6
residual_1 = 20
residual_2 = 1
shortcut_sa = 1
shortcut_ffn = 0

[layer_17]
q_proj = 0
v_proj = 4
residual_1 = 20
residual_2 = 0
shortcut_sa = 20
shortcut_ffn = 20

[layer_18]
q_proj = 0
v_proj = 12
residual_1 = 0
residual_2 = 5
shortcut_sa = 20
shortcut_ffn = 20

[layer_19]
q_proj = 0
v_proj = 5
residual_1 = 4
residual_2 = 5
shortcut_sa = 19
shortcut_ffn = 2

[layer_20]
q_proj = 0
v_proj = 5
residual_1 = 19
residual_2 = 19
shortcut_sa = 19
shortcut_ffn = 5

[layer_21]
q_proj = 0
v_proj = 5
residual_1 = 2
residual_2 = 2
shortcut_sa = 8
shortcut_ffn = 7

[layer_22]
q_proj = 0
v_proj = 2
residual_1 = 6
residual_2 = 19
shortcut_sa = 18
shortcut_ffn = 9

[layer_23]
q_proj = 0
v_proj = 9
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 1
