total_reallocation_number = 20

[layer_0]
q_proj = 0
v_proj = 2
residual_1 = 0
residual_2 = 0
shortcut_sa = 0

[layer_1]
q_proj = 0
v_proj = 18
residual_1 = 0
residual_2 = 0
shortcut_sa = 2
shortcut_ffn = 0

[layer_2]
q_proj = 0
v_proj = 17
residual_1 = 0
residual_2 = 0
shortcut_sa = 4
shortcut_ffn = 0

[layer_3]
q_proj = 0
v_proj = 16
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_4]
q_proj = 0
v_proj = 19
residual_1 = 0
residual_2 = 4
shortcut_sa = 4
shortcut_ffn = 6

[layer_5]
q_proj = 0
v_proj = 18
residual_1 = 0
residual_2 = 7
shortcut_sa = 6
shortcut_ffn = 0

[layer_6]
q_proj = 0
v_proj = 20
residual_1 = 0
residual_2 = 0
shortcut_sa = 3
shortcut_ffn = 0

[layer_7]
q_proj = 0
v_proj = 18
residual_1 = 0
residual_2 = 1
shortcut_sa = 3
shortcut_ffn = 1

[layer_8]
q_proj = 0
v_proj = 19
residual_1 = 3
residual_2 = 1
shortcut_sa = 7
shortcut_ffn = 3

[layer_9]
q_proj = 0
v_proj = 20
residual_1 = 2
residual_2 = 7
shortcut_sa = 13
shortcut_ffn = 0

[layer_10]
q_proj = 16
v_proj = 20
residual_1 = 0
residual_2 = 6
shortcut_sa = 0
shortcut_ffn = 0

[layer_11]
q_proj = 1
v_proj = 20
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_12]
q_proj = 6
v_proj = 20
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_13]
q_proj = 0
v_proj = 20
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_14]
q_proj = 0
v_proj = 19
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_15]
q_proj = 0
v_proj = 19
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_16]
q_proj = 0
v_proj = 16
residual_1 = 2
residual_2 = 0
shortcut_sa = 1
shortcut_ffn = 0

[layer_17]
q_proj = 0
v_proj = 14
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_18]
q_proj = 0
v_proj = 17
residual_1 = 0
residual_2 = 20
shortcut_sa = 3
shortcut_ffn = 20

[layer_19]
q_proj = 0
v_proj = 9
residual_1 = 19
residual_2 = 7
shortcut_sa = 20
shortcut_ffn = 5

[layer_20]
q_proj = 0
v_proj = 16
residual_1 = 2
residual_2 = 18
shortcut_sa = 18
shortcut_ffn = 4

[layer_21]
q_proj = 0
v_proj = 14
residual_1 = 11
residual_2 = 2
shortcut_sa = 14
shortcut_ffn = 15

[layer_22]
q_proj = 0
v_proj = 17
residual_1 = 3
residual_2 = 3
shortcut_sa = 8
shortcut_ffn = 14

[layer_23]
q_proj = 0
v_proj = 15
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 2
