total_reallocation_number = 100

[layer_0]
q_proj = 0
v_proj = 0
residual_1 = 0
residual_2 = 0
shortcut_sa = 0

[layer_1]
q_proj = 0
v_proj = 3
residual_1 = 0
residual_2 = 0
shortcut_sa = 63
shortcut_ffn = 0

[layer_2]
q_proj = 0
v_proj = 29
residual_1 = 0
residual_2 = 0
shortcut_sa = 68
shortcut_ffn = 0

[layer_3]
q_proj = 0
v_proj = 50
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_4]
q_proj = 0
v_proj = 68
residual_1 = 0
residual_2 = 1
shortcut_sa = 17
shortcut_ffn = 30

[layer_5]
q_proj = 0
v_proj = 52
residual_1 = 0
residual_2 = 76
shortcut_sa = 7
shortcut_ffn = 31

[layer_6]
q_proj = 0
v_proj = 90
residual_1 = 42
residual_2 = 0
shortcut_sa = 86
shortcut_ffn = 0

[layer_7]
q_proj = 0
v_proj = 78
residual_1 = 2
residual_2 = 84
shortcut_sa = 87
shortcut_ffn = 69

[layer_8]
q_proj = 0
v_proj = 89
residual_1 = 42
residual_2 = 81
shortcut_sa = 87
shortcut_ffn = 84

[layer_9]
q_proj = 0
v_proj = 93
residual_1 = 87
residual_2 = 88
shortcut_sa = 88
shortcut_ffn = 5

[layer_10]
q_proj = 83
v_proj = 100
residual_1 = 1
residual_2 = 47
shortcut_sa = 0
shortcut_ffn = 76

[layer_11]
q_proj = 0
v_proj = 86
residual_1 = 0
residual_2 = 8
shortcut_sa = 47
shortcut_ffn = 0

[layer_12]
q_proj = 0
v_proj = 83
residual_1 = 0
residual_2 = 0
shortcut_sa = 2
shortcut_ffn = 2

[layer_13]
q_proj = 0
v_proj = 100
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_14]
q_proj = 0
v_proj = 44
residual_1 = 0
residual_2 = 0
shortcut_sa = 4
shortcut_ffn = 0

[layer_15]
q_proj = 0
v_proj = 17
residual_1 = 5
residual_2 = 0
shortcut_sa = 2
shortcut_ffn = 100

[layer_16]
q_proj = 0
v_proj = 16
residual_1 = 99
residual_2 = 3
shortcut_sa = 1
shortcut_ffn = 0

[layer_17]
q_proj = 0
v_proj = 22
residual_1 = 85
residual_2 = 1
shortcut_sa = 100
shortcut_ffn = 1

[layer_18]
q_proj = 0
v_proj = 28
residual_1 = 3
residual_2 = 30
shortcut_sa = 74
shortcut_ffn = 97

[layer_19]
q_proj = 0
v_proj = 19
residual_1 = 13
residual_2 = 27
shortcut_sa = 59
shortcut_ffn = 11

[layer_20]
q_proj = 0
v_proj = 14
residual_1 = 15
residual_2 = 49
shortcut_sa = 46
shortcut_ffn = 13

[layer_21]
q_proj = 0
v_proj = 12
residual_1 = 20
residual_2 = 16
shortcut_sa = 15
shortcut_ffn = 16

[layer_22]
q_proj = 0
v_proj = 10
residual_1 = 8
residual_2 = 11
shortcut_sa = 34
shortcut_ffn = 12

[layer_23]
q_proj = 0
v_proj = 14
residual_1 = 0
residual_2 = 6
shortcut_sa = 7
shortcut_ffn = 9
