total_reallocation_number = 50

[layer_0]
q_proj = 0
v_proj = 1
residual_1 = 1
residual_2 = 0
shortcut_sa = 0

[layer_1]
q_proj = 0
v_proj = 49
residual_1 = 0
residual_2 = 0
shortcut_sa = 1
shortcut_ffn = 0

[layer_2]
q_proj = 0
v_proj = 49
residual_1 = 0
residual_2 = 0
shortcut_sa = 37
shortcut_ffn = 0

[layer_3]
q_proj = 0
v_proj = 49
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_4]
q_proj = 0
v_proj = 49
residual_1 = 0
residual_2 = 26
shortcut_sa = 37
shortcut_ffn = 0

[layer_5]
q_proj = 0
v_proj = 49
residual_1 = 1
residual_2 = 1
shortcut_sa = 1
shortcut_ffn = 4

[layer_6]
q_proj = 0
v_proj = 49
residual_1 = 1
residual_2 = 0
shortcut_sa = 30
shortcut_ffn = 0

[layer_7]
q_proj = 0
v_proj = 38
residual_1 = 0
residual_2 = 1
shortcut_sa = 36
shortcut_ffn = 1

[layer_8]
q_proj = 0
v_proj = 48
residual_1 = 0
residual_2 = 1
shortcut_sa = 19
shortcut_ffn = 18

[layer_9]
q_proj = 0
v_proj = 50
residual_1 = 1
residual_2 = 0
shortcut_sa = 36
shortcut_ffn = 0

[layer_10]
q_proj = 0
v_proj = 50
residual_1 = 0
residual_2 = 1
shortcut_sa = 1
shortcut_ffn = 1

[layer_11]
q_proj = 0
v_proj = 50
residual_1 = 0
residual_2 = 0
shortcut_sa = 1
shortcut_ffn = 0

[layer_12]
q_proj = 0
v_proj = 50
residual_1 = 0
residual_2 = 0
shortcut_sa = 2
shortcut_ffn = 0

[layer_13]
q_proj = 0
v_proj = 50
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_14]
q_proj = 0
v_proj = 50
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_15]
q_proj = 0
v_proj = 50
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 1

[layer_16]
q_proj = 0
v_proj = 50
residual_1 = 50
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_17]
q_proj = 0
v_proj = 50
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 50

[layer_18]
q_proj = 0
v_proj = 50
residual_1 = 0
residual_2 = 5
shortcut_sa = 6
shortcut_ffn = 50

[layer_19]
q_proj = 0
v_proj = 50
residual_1 = 49
residual_2 = 5
shortcut_sa = 45
shortcut_ffn = 50

[layer_20]
q_proj = 0
v_proj = 50
residual_1 = 4
residual_2 = 16
shortcut_sa = 10
shortcut_ffn = 4

[layer_21]
q_proj = 0
v_proj = 9
residual_1 = 23
residual_2 = 11
shortcut_sa = 10
shortcut_ffn = 50

[layer_22]
q_proj = 0
v_proj = 6
residual_1 = 8
residual_2 = 34
shortcut_sa = 27
shortcut_ffn = 31

[layer_23]
q_proj = 0
v_proj = 6
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0
