total_reallocation_number = 50

[layer_0]
q_proj = 0
v_proj = 0
residual_1 = 1
residual_2 = 0
shortcut_sa = 0

[layer_1]
q_proj = 0
v_proj = 0
residual_1 = 1
residual_2 = 1
shortcut_sa = 2
shortcut_ffn = 1

[layer_2]
q_proj = 0
v_proj = 38
residual_1 = 0
residual_2 = 0
shortcut_sa = 38
shortcut_ffn = 0

[layer_3]
q_proj = 0
v_proj = 0
residual_1 = 1
residual_2 = 0
shortcut_sa = 1
shortcut_ffn = 0

[layer_4]
q_proj = 0
v_proj = 1
residual_1 = 0
residual_2 = 38
shortcut_sa = 9
shortcut_ffn = 1

[layer_5]
q_proj = 0
v_proj = 0
residual_1 = 2
residual_2 = 2
shortcut_sa = 5
shortcut_ffn = 14

[layer_6]
q_proj = 0
v_proj = 42
residual_1 = 1
residual_2 = 1
shortcut_sa = 5
shortcut_ffn = 1

[layer_7]
q_proj = 0
v_proj = 0
residual_1 = 1
residual_2 = 1
shortcut_sa = 21
shortcut_ffn = 1

[layer_8]
q_proj = 0
v_proj = 1
residual_1 = 1
residual_2 = 1
shortcut_sa = 22
shortcut_ffn = 1

[layer_9]
q_proj = 0
v_proj = 49
residual_1 = 1
residual_2 = 0
shortcut_sa = 26
shortcut_ffn = 1

[layer_10]
q_proj = 0
v_proj = 50
residual_1 = 1
residual_2 = 2
shortcut_sa = 2
shortcut_ffn = 1

[layer_11]
q_proj = 0
v_proj = 49
residual_1 = 1
residual_2 = 1
shortcut_sa = 2
shortcut_ffn = 1

[layer_12]
q_proj = 0
v_proj = 1
residual_1 = 1
residual_2 = 0
shortcut_sa = 1
shortcut_ffn = 1

[layer_13]
q_proj = 0
v_proj = 50
residual_1 = 0
residual_2 = 0
shortcut_sa = 5
shortcut_ffn = 0

[layer_14]
q_proj = 0
v_proj = 50
residual_1 = 0
residual_2 = 0
shortcut_sa = 1
shortcut_ffn = 0

[layer_15]
q_proj = 0
v_proj = 50
residual_1 = 0
residual_2 = 0
shortcut_sa = 50
shortcut_ffn = 50

[layer_16]
q_proj = 0
v_proj = 18
residual_1 = 50
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_17]
q_proj = 0
v_proj = 50
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 50

[layer_18]
q_proj = 0
v_proj = 49
residual_1 = 0
residual_2 = 50
shortcut_sa = 50
shortcut_ffn = 50

[layer_19]
q_proj = 0
v_proj = 43
residual_1 = 50
residual_2 = 50
shortcut_sa = 50
shortcut_ffn = 50

[layer_20]
q_proj = 0
v_proj = 50
residual_1 = 8
residual_2 = 42
shortcut_sa = 23
shortcut_ffn = 11

[layer_21]
q_proj = 0
v_proj = 3
residual_1 = 36
residual_2 = 39
shortcut_sa = 29
shortcut_ffn = 45

[layer_22]
q_proj = 0
v_proj = 3
residual_1 = 26
residual_2 = 35
shortcut_sa = 45
shortcut_ffn = 45

[layer_23]
q_proj = 0
v_proj = 3
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 44
