total_reallocation_number = 100

[layer_0]
q_proj = 0
v_proj = 0
residual_1 = 1
residual_2 = 0
shortcut_sa = 0

[layer_1]
q_proj = 0
v_proj = 4
residual_1 = 0
residual_2 = 0
shortcut_sa = 71
shortcut_ffn = 1

[layer_2]
q_proj = 0
v_proj = 65
residual_1 = 0
residual_2 = 0
shortcut_sa = 2
shortcut_ffn = 0

[layer_3]
q_proj = 0
v_proj = 2
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_4]
q_proj = 0
v_proj = 78
residual_1 = 0
residual_2 = 9
shortcut_sa = 0
shortcut_ffn = 2

[layer_5]
q_proj = 0
v_proj = 6
residual_1 = 0
residual_2 = 1
shortcut_sa = 1
shortcut_ffn = 0

[layer_6]
q_proj = 0
v_proj = 2
residual_1 = 0
residual_2 = 0
shortcut_sa = 4
shortcut_ffn = 0

[layer_7]
q_proj = 0
v_proj = 0
residual_1 = 3
residual_2 = 4
shortcut_sa = 65
shortcut_ffn = 4

[layer_8]
q_proj = 0
v_proj = 7
residual_1 = 0
residual_2 = 7
shortcut_sa = 82
shortcut_ffn = 3

[layer_9]
q_proj = 0
v_proj = 95
residual_1 = 2
residual_2 = 29
shortcut_sa = 74
shortcut_ffn = 0

[layer_10]
q_proj = 1
v_proj = 100
residual_1 = 0
residual_2 = 30
shortcut_sa = 39
shortcut_ffn = 2

[layer_11]
q_proj = 0
v_proj = 76
residual_1 = 3
residual_2 = 1
shortcut_sa = 5
shortcut_ffn = 1

[layer_12]
q_proj = 0
v_proj = 5
residual_1 = 0
residual_2 = 1
shortcut_sa = 14
shortcut_ffn = 2

[layer_13]
q_proj = 0
v_proj = 99
residual_1 = 0
residual_2 = 3
shortcut_sa = 13
shortcut_ffn = 0

[layer_14]
q_proj = 0
v_proj = 99
residual_1 = 0
residual_2 = 0
shortcut_sa = 3
shortcut_ffn = 2

[layer_15]
q_proj = 0
v_proj = 21
residual_1 = 8
residual_2 = 2
shortcut_sa = 20
shortcut_ffn = 100

[layer_16]
q_proj = 0
v_proj = 99
residual_1 = 100
residual_2 = 2
shortcut_sa = 3
shortcut_ffn = 1

[layer_17]
q_proj = 0
v_proj = 46
residual_1 = 100
residual_2 = 6
shortcut_sa = 33
shortcut_ffn = 100

[layer_18]
q_proj = 0
v_proj = 100
residual_1 = 0
residual_2 = 100
shortcut_sa = 100
shortcut_ffn = 100

[layer_19]
q_proj = 0
v_proj = 100
residual_1 = 100
residual_2 = 100
shortcut_sa = 100
shortcut_ffn = 100

[layer_20]
q_proj = 0
v_proj = 100
residual_1 = 22
residual_2 = 41
shortcut_sa = 97
shortcut_ffn = 61

[layer_21]
q_proj = 0
v_proj = 15
residual_1 = 100
residual_2 = 100
shortcut_sa = 79
shortcut_ffn = 100

[layer_22]
q_proj = 0
v_proj = 69
residual_1 = 22
residual_2 = 17
shortcut_sa = 21
shortcut_ffn = 80

[layer_23]
q_proj = 0
v_proj = 11
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 1
