total_reallocation_number = 100

[layer_0]
q_proj = 0
v_proj = 0
residual_1 = 2
residual_2 = 0
shortcut_sa = 0

[layer_1]
q_proj = 0
v_proj = 2
residual_1 = 0
residual_2 = 0
shortcut_sa = 73
shortcut_ffn = 4

[layer_2]
q_proj = 0
v_proj = 19
residual_1 = 0
residual_2 = 0
shortcut_sa = 77
shortcut_ffn = 0

[layer_3]
q_proj = 0
v_proj = 0
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_4]
q_proj = 0
v_proj = 77
residual_1 = 0
residual_2 = 72
shortcut_sa = 0
shortcut_ffn = 1

[layer_5]
q_proj = 0
v_proj = 2
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_6]
q_proj = 0
v_proj = 92
residual_1 = 0
residual_2 = 0
shortcut_sa = 2
shortcut_ffn = 0

[layer_7]
q_proj = 0
v_proj = 0
residual_1 = 18
residual_2 = 59
shortcut_sa = 64
shortcut_ffn = 0

[layer_8]
q_proj = 0
v_proj = 64
residual_1 = 0
residual_2 = 0
shortcut_sa = 52
shortcut_ffn = 72

[layer_9]
q_proj = 0
v_proj = 98
residual_1 = 1
residual_2 = 77
shortcut_sa = 96
shortcut_ffn = 0

[layer_10]
q_proj = 39
v_proj = 100
residual_1 = 0
residual_2 = 89
shortcut_sa = 84
shortcut_ffn = 0

[layer_11]
q_proj = 0
v_proj = 98
residual_1 = 1
residual_2 = 0
shortcut_sa = 91
shortcut_ffn = 2

[layer_12]
q_proj = 0
v_proj = 92
residual_1 = 0
residual_2 = 0
shortcut_sa = 87
shortcut_ffn = 0

[layer_13]
q_proj = 0
v_proj = 100
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_14]
q_proj = 0
v_proj = 35
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_15]
q_proj = 0
v_proj = 100
residual_1 = 0
residual_2 = 0
shortcut_sa = 4
shortcut_ffn = 99

[layer_16]
q_proj = 0
v_proj = 12
residual_1 = 2
residual_2 = 1
shortcut_sa = 0
shortcut_ffn = 0

[layer_17]
q_proj = 0
v_proj = 39
residual_1 = 99
residual_2 = 0
shortcut_sa = 86
shortcut_ffn = 100

[layer_18]
q_proj = 0
v_proj = 28
residual_1 = 0
residual_2 = 96
shortcut_sa = 100
shortcut_ffn = 100

[layer_19]
q_proj = 0
v_proj = 82
residual_1 = 52
residual_2 = 79
shortcut_sa = 100
shortcut_ffn = 100

[layer_20]
q_proj = 0
v_proj = 99
residual_1 = 20
residual_2 = 31
shortcut_sa = 42
shortcut_ffn = 35

[layer_21]
q_proj = 0
v_proj = 4
residual_1 = 10
residual_2 = 92
shortcut_sa = 25
shortcut_ffn = 10

[layer_22]
q_proj = 0
v_proj = 4
residual_1 = 5
residual_2 = 9
shortcut_sa = 45
shortcut_ffn = 21

[layer_23]
q_proj = 0
v_proj = 14
residual_1 = 0
residual_2 = 0
shortcut_sa = 8
shortcut_ffn = 5
