total_reallocation_number = 100

[layer_0]
q_proj = 0
v_proj = 0
residual_1 = 4
residual_2 = 3
shortcut_sa = 0

[layer_1]
q_proj = 0
v_proj = 88
residual_1 = 0
residual_2 = 0
shortcut_sa = 1
shortcut_ffn = 1

[layer_2]
q_proj = 0
v_proj = 2
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_3]
q_proj = 0
v_proj = 23
residual_1 = 1
residual_2 = 1
shortcut_sa = 86
shortcut_ffn = 1

[layer_4]
q_proj = 0
v_proj = 78
residual_1 = 1
residual_2 = 15
shortcut_sa = 3
shortcut_ffn = 1

[layer_5]
q_proj = 0
v_proj = 54
residual_1 = 1
residual_2 = 88
shortcut_sa = 83
shortcut_ffn = 90

[layer_6]
q_proj = 0
v_proj = 85
residual_1 = 90
residual_2 = 48
shortcut_sa = 90
shortcut_ffn = 77

[layer_7]
q_proj = 0
v_proj = 92
residual_1 = 0
residual_2 = 88
shortcut_sa = 91
shortcut_ffn = 0

[layer_8]
q_proj = 0
v_proj = 93
residual_1 = 5
residual_2 = 24
shortcut_sa = 66
shortcut_ffn = 76

[layer_9]
q_proj = 0
v_proj = 93
residual_1 = 64
residual_2 = 93
shortcut_sa = 76
shortcut_ffn = 63

[layer_10]
q_proj = 75
v_proj = 97
residual_1 = 0
residual_2 = 37
shortcut_sa = 1
shortcut_ffn = 2

[layer_11]
q_proj = 0
v_proj = 95
residual_1 = 0
residual_2 = 6
shortcut_sa = 84
shortcut_ffn = 1

[layer_12]
q_proj = 0
v_proj = 100
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_13]
q_proj = 0
v_proj = 88
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 2

[layer_14]
q_proj = 0
v_proj = 22
residual_1 = 0
residual_2 = 0
shortcut_sa = 5
shortcut_ffn = 0

[layer_15]
q_proj = 0
v_proj = 6
residual_1 = 0
residual_2 = 2
shortcut_sa = 98
shortcut_ffn = 97

[layer_16]
q_proj = 0
v_proj = 15
residual_1 = 12
residual_2 = 2
shortcut_sa = 100
shortcut_ffn = 1

[layer_17]
q_proj = 0
v_proj = 27
residual_1 = 0
residual_2 = 0
shortcut_sa = 98
shortcut_ffn = 0

[layer_18]
q_proj = 0
v_proj = 15
residual_1 = 11
residual_2 = 13
shortcut_sa = 73
shortcut_ffn = 2

[layer_19]
q_proj = 0
v_proj = 8
residual_1 = 32
residual_2 = 10
shortcut_sa = 53
shortcut_ffn = 93

[layer_20]
q_proj = 0
v_proj = 12
residual_1 = 7
residual_2 = 11
shortcut_sa = 29
shortcut_ffn = 49

[layer_21]
q_proj = 0
v_proj = 11
residual_1 = 18
residual_2 = 16
shortcut_sa = 19
shortcut_ffn = 25

[layer_22]
q_proj = 0
v_proj = 14
residual_1 = 14
residual_2 = 13
shortcut_sa = 18
shortcut_ffn = 8

[layer_23]
q_proj = 0
v_proj = 7
residual_1 = 5
residual_2 = 0
shortcut_sa = 2
shortcut_ffn = 0
