[layer_residual]
granularity = "network"

[layer_residual.default]
r = 8
proj_dropout = 0.0
projector_name = "ags-layer-res-network-opt"
init_lora_weghts = true
fan_in_fan_out = false
disable_projector = false

[layer_residual.all_layers]
r = 8
proj_dropout = 0.0
projector_name = "ags-layer-res-network-opt"
disable_projector = false


[head_residual]
granularity = "network"

[head_residual.default]
r = 0
proj_dropout = 0.0
projector_name = "ags-layer-res-network-opt"
init_lora_weghts = true
fan_in_fan_out = false
disable_projector = true
