granularity = "layer"

[default]
r = 0
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-importance-alpaca"
init_lora_weghts = true
fan_in_fan_out = false
disable_adapter = true

[model_layer_20.v_proj]
r = 32
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-importance-alpaca"
disable_adapter = false

[model_layer_20.q_proj]
r = 32
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-importance-alpaca"
disable_adapter = false

[model_layer_13.v_proj]
r = 32
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-importance-alpaca"
disable_adapter = false

[model_layer_18.q_proj]
r = 32
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-importance-alpaca"
disable_adapter = false

[model_layer_18.v_proj]
r = 32
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-importance-alpaca"
disable_adapter = false

[model_layer_11.q_proj]
r = 32
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-importance-alpaca"
disable_adapter = false

[model_layer_14.q_proj]
r = 32
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-importance-alpaca"
disable_adapter = false

[model_layer_14.v_proj]
r = 32
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-importance-alpaca"
disable_adapter = false

[model_layer_16.q_proj]
r = 32
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-importance-alpaca"
disable_adapter = false

[model_layer_17.v_proj]
r = 32
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-importance-alpaca"
disable_adapter = false

[model_layer_17.q_proj]
r = 32
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-importance-alpaca"
disable_adapter = false

[model_layer_19.v_proj]
r = 32
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-importance-alpaca"
disable_adapter = false
