granularity = "layer"

[default]
r = 0
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-importance-sst2"
init_lora_weghts = true
fan_in_fan_out = false
disable_adapter = true

[model_layer_0.v_proj]
r = 32
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-importance-sst2"
disable_adapter = false

[model_layer_2.v_proj]
r = 32
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-importance-sst2"
disable_adapter = false

[model_layer_12.v_proj]
r = 32
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-importance-sst2"
disable_adapter = false

[model_layer_13.v_proj]
r = 32
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-importance-sst2"
disable_adapter = false

[model_layer_3.v_proj]
r = 32
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-importance-sst2"
disable_adapter = false

[model_layer_11.v_proj]
r = 32
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-importance-sst2"
disable_adapter = false

[model_layer_16.q_proj]
r = 32
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-importance-sst2"
disable_adapter = false

[model_layer_17.v_proj]
r = 32
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-importance-sst2"
disable_adapter = false

[model_layer_21.v_proj]
r = 32
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-importance-sst2"
disable_adapter = false

[model_layer_5.v_proj]
r = 32
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-importance-sst2"
disable_adapter = false

[model_layer_6.v_proj]
r = 32
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-importance-sst2"
disable_adapter = false

[model_layer_20.v_proj]
r = 32
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-importance-sst2"
disable_adapter = false
