total_reallocation_number = 100

[layer_0]
q_proj = 0
v_proj = 1
residual_1 = 98
residual_2 = 98
shortcut_sa = 0

[layer_1]
q_proj = 0
v_proj = 96
residual_1 = 3
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 44

[layer_2]
q_proj = 0
v_proj = 17
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_3]
q_proj = 0
v_proj = 81
residual_1 = 0
residual_2 = 1
shortcut_sa = 0
shortcut_ffn = 0

[layer_4]
q_proj = 0
v_proj = 3
residual_1 = 0
residual_2 = 7
shortcut_sa = 1
shortcut_ffn = 0

[layer_5]
q_proj = 0
v_proj = 76
residual_1 = 0
residual_2 = 1
shortcut_sa = 12
shortcut_ffn = 1

[layer_6]
q_proj = 0
v_proj = 20
residual_1 = 10
residual_2 = 90
shortcut_sa = 74
shortcut_ffn = 64

[layer_7]
q_proj = 0
v_proj = 93
residual_1 = 3
residual_2 = 3
shortcut_sa = 75
shortcut_ffn = 3

[layer_8]
q_proj = 0
v_proj = 79
residual_1 = 34
residual_2 = 66
shortcut_sa = 76
shortcut_ffn = 0

[layer_9]
q_proj = 0
v_proj = 96
residual_1 = 69
residual_2 = 98
shortcut_sa = 98
shortcut_ffn = 74

[layer_10]
q_proj = 70
v_proj = 98
residual_1 = 85
residual_2 = 77
shortcut_sa = 96
shortcut_ffn = 60

[layer_11]
q_proj = 0
v_proj = 99
residual_1 = 0
residual_2 = 3
shortcut_sa = 93
shortcut_ffn = 0

[layer_12]
q_proj = 0
v_proj = 100
residual_1 = 0
residual_2 = 8
shortcut_sa = 16
shortcut_ffn = 0

[layer_13]
q_proj = 0
v_proj = 86
residual_1 = 0
residual_2 = 0
shortcut_sa = 2
shortcut_ffn = 0

[layer_14]
q_proj = 0
v_proj = 7
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_15]
q_proj = 0
v_proj = 4
residual_1 = 0
residual_2 = 0
shortcut_sa = 100
shortcut_ffn = 0

[layer_16]
q_proj = 0
v_proj = 50
residual_1 = 0
residual_2 = 0
shortcut_sa = 98
shortcut_ffn = 0

[layer_17]
q_proj = 0
v_proj = 55
residual_1 = 2
residual_2 = 92
shortcut_sa = 94
shortcut_ffn = 0

[layer_18]
q_proj = 0
v_proj = 11
residual_1 = 0
residual_2 = 3
shortcut_sa = 90
shortcut_ffn = 1

[layer_19]
q_proj = 0
v_proj = 14
residual_1 = 3
residual_2 = 4
shortcut_sa = 69
shortcut_ffn = 3

[layer_20]
q_proj = 0
v_proj = 21
residual_1 = 8
residual_2 = 18
shortcut_sa = 26
shortcut_ffn = 29

[layer_21]
q_proj = 0
v_proj = 9
residual_1 = 25
residual_2 = 39
shortcut_sa = 44
shortcut_ffn = 30

[layer_22]
q_proj = 0
v_proj = 8
residual_1 = 8
residual_2 = 5
shortcut_sa = 20
shortcut_ffn = 35

[layer_23]
q_proj = 0
v_proj = 6
residual_1 = 0
residual_2 = 0
shortcut_sa = 5
shortcut_ffn = 6
