total_reallocation_number = 100

[layer_0]
q_proj = 0
v_proj = 85
residual_1 = 17
residual_2 = 1
shortcut_sa = 0

[layer_1]
q_proj = 2
v_proj = 97
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_2]
q_proj = 0
v_proj = 99
residual_1 = 0
residual_2 = 0
shortcut_sa = 1
shortcut_ffn = 0

[layer_3]
q_proj = 0
v_proj = 94
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_4]
q_proj = 0
v_proj = 100
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_5]
q_proj = 0
v_proj = 99
residual_1 = 0
residual_2 = 41
shortcut_sa = 52
shortcut_ffn = 0

[layer_6]
q_proj = 0
v_proj = 99
residual_1 = 0
residual_2 = 64
shortcut_sa = 62
shortcut_ffn = 1

[layer_7]
q_proj = 0
v_proj = 99
residual_1 = 2
residual_2 = 32
shortcut_sa = 0
shortcut_ffn = 1

[layer_8]
q_proj = 0
v_proj = 99
residual_1 = 2
residual_2 = 2
shortcut_sa = 86
shortcut_ffn = 2

[layer_9]
q_proj = 0
v_proj = 100
residual_1 = 46
residual_2 = 95
shortcut_sa = 95
shortcut_ffn = 58

[layer_10]
q_proj = 95
v_proj = 100
residual_1 = 0
residual_2 = 84
shortcut_sa = 92
shortcut_ffn = 50

[layer_11]
q_proj = 1
v_proj = 100
residual_1 = 0
residual_2 = 0
shortcut_sa = 29
shortcut_ffn = 0

[layer_12]
q_proj = 63
v_proj = 100
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_13]
q_proj = 0
v_proj = 100
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_14]
q_proj = 1
v_proj = 100
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_15]
q_proj = 1
v_proj = 100
residual_1 = 0
residual_2 = 0
shortcut_sa = 73
shortcut_ffn = 0

[layer_16]
q_proj = 0
v_proj = 91
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_17]
q_proj = 0
v_proj = 95
residual_1 = 0
residual_2 = 4
shortcut_sa = 99
shortcut_ffn = 1

[layer_18]
q_proj = 0
v_proj = 77
residual_1 = 0
residual_2 = 3
shortcut_sa = 2
shortcut_ffn = 2

[layer_19]
q_proj = 0
v_proj = 96
residual_1 = 2
residual_2 = 2
shortcut_sa = 54
shortcut_ffn = 3

[layer_20]
q_proj = 0
v_proj = 61
residual_1 = 6
residual_2 = 4
shortcut_sa = 34
shortcut_ffn = 7

[layer_21]
q_proj = 0
v_proj = 27
residual_1 = 3
residual_2 = 12
shortcut_sa = 61
shortcut_ffn = 12

[layer_22]
q_proj = 0
v_proj = 4
residual_1 = 10
residual_2 = 4
shortcut_sa = 11
shortcut_ffn = 35

[layer_23]
q_proj = 0
v_proj = 54
residual_1 = 0
residual_2 = 2
shortcut_sa = 0
shortcut_ffn = 0
