total_reallocation_number = 100

[layer_0]
q_proj = 0
v_proj = 0
residual_1 = 33
residual_2 = 0
shortcut_sa = 0

[layer_1]
q_proj = 0
v_proj = 2
residual_1 = 0
residual_2 = 0
shortcut_sa = 4
shortcut_ffn = 0

[layer_2]
q_proj = 0
v_proj = 42
residual_1 = 0
residual_2 = 0
shortcut_sa = 38
shortcut_ffn = 0

[layer_3]
q_proj = 0
v_proj = 60
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_4]
q_proj = 0
v_proj = 95
residual_1 = 1
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_5]
q_proj = 0
v_proj = 97
residual_1 = 0
residual_2 = 30
shortcut_sa = 69
shortcut_ffn = 1

[layer_6]
q_proj = 0
v_proj = 2
residual_1 = 1
residual_2 = 76
shortcut_sa = 87
shortcut_ffn = 38

[layer_7]
q_proj = 0
v_proj = 47
residual_1 = 1
residual_2 = 5
shortcut_sa = 1
shortcut_ffn = 18

[layer_8]
q_proj = 0
v_proj = 2
residual_1 = 65
residual_2 = 1
shortcut_sa = 89
shortcut_ffn = 1

[layer_9]
q_proj = 0
v_proj = 96
residual_1 = 8
residual_2 = 94
shortcut_sa = 92
shortcut_ffn = 2

[layer_10]
q_proj = 32
v_proj = 95
residual_1 = 0
residual_2 = 81
shortcut_sa = 92
shortcut_ffn = 70

[layer_11]
q_proj = 0
v_proj = 100
residual_1 = 0
residual_2 = 38
shortcut_sa = 97
shortcut_ffn = 1

[layer_12]
q_proj = 0
v_proj = 87
residual_1 = 0
residual_2 = 0
shortcut_sa = 6
shortcut_ffn = 0

[layer_13]
q_proj = 0
v_proj = 99
residual_1 = 0
residual_2 = 0
shortcut_sa = 1
shortcut_ffn = 0

[layer_14]
q_proj = 0
v_proj = 100
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_15]
q_proj = 0
v_proj = 79
residual_1 = 0
residual_2 = 2
shortcut_sa = 100
shortcut_ffn = 100

[layer_16]
q_proj = 0
v_proj = 19
residual_1 = 1
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 98

[layer_17]
q_proj = 0
v_proj = 58
residual_1 = 1
residual_2 = 1
shortcut_sa = 100
shortcut_ffn = 98

[layer_18]
q_proj = 0
v_proj = 17
residual_1 = 11
residual_2 = 99
shortcut_sa = 1
shortcut_ffn = 4

[layer_19]
q_proj = 0
v_proj = 52
residual_1 = 8
residual_2 = 84
shortcut_sa = 91
shortcut_ffn = 81

[layer_20]
q_proj = 0
v_proj = 4
residual_1 = 10
residual_2 = 18
shortcut_sa = 43
shortcut_ffn = 27

[layer_21]
q_proj = 0
v_proj = 4
residual_1 = 62
residual_2 = 21
shortcut_sa = 70
shortcut_ffn = 69

[layer_22]
q_proj = 0
v_proj = 4
residual_1 = 8
residual_2 = 2
shortcut_sa = 11
shortcut_ffn = 33

[layer_23]
q_proj = 0
v_proj = 7
residual_1 = 0
residual_2 = 2
shortcut_sa = 1
shortcut_ffn = 2
