total_reallocation_number = 100

[layer_0]
q_proj = 0
v_proj = 1
residual_1 = 1
residual_2 = 0
shortcut_sa = 0

[layer_1]
q_proj = 0
v_proj = 99
residual_1 = 0
residual_2 = 0
shortcut_sa = 17
shortcut_ffn = 0

[layer_2]
q_proj = 0
v_proj = 99
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_3]
q_proj = 0
v_proj = 100
residual_1 = 0
residual_2 = 0
shortcut_sa = 3
shortcut_ffn = 0

[layer_4]
q_proj = 0
v_proj = 99
residual_1 = 0
residual_2 = 0
shortcut_sa = 55
shortcut_ffn = 0

[layer_5]
q_proj = 0
v_proj = 99
residual_1 = 0
residual_2 = 2
shortcut_sa = 59
shortcut_ffn = 4

[layer_6]
q_proj = 0
v_proj = 97
residual_1 = 2
residual_2 = 64
shortcut_sa = 63
shortcut_ffn = 3

[layer_7]
q_proj = 0
v_proj = 98
residual_1 = 0
residual_2 = 2
shortcut_sa = 1
shortcut_ffn = 6

[layer_8]
q_proj = 0
v_proj = 100
residual_1 = 0
residual_2 = 39
shortcut_sa = 67
shortcut_ffn = 0

[layer_9]
q_proj = 0
v_proj = 100
residual_1 = 9
residual_2 = 85
shortcut_sa = 81
shortcut_ffn = 4

[layer_10]
q_proj = 87
v_proj = 100
residual_1 = 74
residual_2 = 76
shortcut_sa = 89
shortcut_ffn = 0

[layer_11]
q_proj = 0
v_proj = 100
residual_1 = 0
residual_2 = 0
shortcut_sa = 4
shortcut_ffn = 0

[layer_12]
q_proj = 0
v_proj = 100
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_13]
q_proj = 9
v_proj = 100
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_14]
q_proj = 74
v_proj = 100
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_15]
q_proj = 0
v_proj = 100
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_16]
q_proj = 0
v_proj = 99
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_17]
q_proj = 0
v_proj = 97
residual_1 = 0
residual_2 = 1
shortcut_sa = 99
shortcut_ffn = 0

[layer_18]
q_proj = 0
v_proj = 100
residual_1 = 0
residual_2 = 1
shortcut_sa = 100
shortcut_ffn = 0

[layer_19]
q_proj = 0
v_proj = 100
residual_1 = 0
residual_2 = 4
shortcut_sa = 69
shortcut_ffn = 0

[layer_20]
q_proj = 0
v_proj = 96
residual_1 = 2
residual_2 = 33
shortcut_sa = 16
shortcut_ffn = 26

[layer_21]
q_proj = 0
v_proj = 29
residual_1 = 27
residual_2 = 30
shortcut_sa = 55
shortcut_ffn = 35

[layer_22]
q_proj = 0
v_proj = 17
residual_1 = 5
residual_2 = 3
shortcut_sa = 10
shortcut_ffn = 29

[layer_23]
q_proj = 0
v_proj = 45
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0
