total_reallocation_number = 100

[layer_0]
q_proj = 0
v_proj = 0

[layer_1]
q_proj = 0
v_proj = 0

[layer_2]
q_proj = 0
v_proj = 0

[layer_3]
q_proj = 0
v_proj = 0

[layer_4]
q_proj = 0
v_proj = 0

[layer_5]
q_proj = 0
v_proj = 0

[layer_6]
q_proj = 0
v_proj = 0

[layer_7]
q_proj = 0
v_proj = 0

[layer_8]
q_proj = 0
v_proj = 0

[layer_9]
q_proj = 0
v_proj = 0

[layer_10]
q_proj = 0
v_proj = 0

[layer_11]
q_proj = 0
v_proj = 0

[layer_12]
q_proj = 0
v_proj = 0

[layer_13]
q_proj = 0
v_proj = 0

[layer_14]
q_proj = 0
v_proj = 0

[layer_15]
q_proj = 0
v_proj = 7

[layer_16]
q_proj = 0
v_proj = 99

[layer_17]
q_proj = 0
v_proj = 100

[layer_18]
q_proj = 12
v_proj = 100

[layer_19]
q_proj = 0
v_proj = 99

[layer_20]
q_proj = 83
v_proj = 100

[layer_21]
q_proj = 100
v_proj = 100

[layer_22]
q_proj = 100
v_proj = 100

[layer_23]
q_proj = 100
v_proj = 100
