# basics
model = "facebook/opt-125m"
dataset = "rte"
# training
training_optimizer = "adamw"
#learning_rate = 1e-5
weight_decay = 0.01
#max_epochs = 15
batch_size = 32
log_every_n_steps = 10
# torch lightning
task = "classification"
#num_workers = 0
num_devices = 1
#accelerator = "cpu"
project_dir = "./ags_output"