[layer0]
v_proj = 1

[layer1]
v_proj = 1

[layer2]
v_proj = 1

[layer3]
v_proj = 1

[layer4]
v_proj = 1

[layer5]
v_proj = 1

[layer6]
v_proj = 1

[layer7]
v_proj = 1

[layer8]
v_proj = 1

[layer9]
v_proj = 1

[layer10]
v_proj = 1

[layer11]
v_proj = 1

[layer12]
v_proj = 1

[layer13]
v_proj = 1

[layer14]
v_proj = 1

[layer15]
v_proj = 1

[layer16]
v_proj = 1

[layer17]
v_proj = 1

[layer18]
v_proj = 1

[layer19]
v_proj = 1

[layer20]
v_proj = 1

[layer21]
v_proj = 1

[layer22]
v_proj = 1

[layer23]
v_proj = 1
