granularity = "layer"

[default]
r = 0
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-top-opt350m"
init_lora_weghts = true
fan_in_fan_out = false
disable_adapter = false

[model_layer_16.q_proj]
r = 24
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-top-opt350m"
disable_adapter = false

[model_layer_16.k_proj]
r = 0
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-top-opt350m"
disable_adapter = true

[model_layer_16.v_proj]
r = 24
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-top-opt350m"
disable_adapter = false

[model_layer_16.o_proj]
r = 0
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-top-opt350m"
disable_adapter = true

[model_layer_16.w1]
r = 0
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-top-opt350m"
disable_adapter = true

[model_layer_16.w2]
r = 0
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-top-opt350m"
disable_adapter = true

[model_layer_17.q_proj]
r = 24
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-top-opt350m"
disable_adapter = false

[model_layer_17.k_proj]
r = 0
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-top-opt350m"
disable_adapter = true

[model_layer_17.v_proj]
r = 24
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-top-opt350m"
disable_adapter = false

[model_layer_17.o_proj]
r = 0
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-top-opt350m"
disable_adapter = true

[model_layer_17.w1]
r = 0
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-top-opt350m"
disable_adapter = true

[model_layer_17.w2]
r = 0
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-top-opt350m"
disable_adapter = true

[model_layer_18.q_proj]
r = 24
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-top-opt350m"
disable_adapter = false

[model_layer_18.k_proj]
r = 0
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-top-opt350m"
disable_adapter = true

[model_layer_18.v_proj]
r = 24
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-top-opt350m"
disable_adapter = false

[model_layer_18.o_proj]
r = 0
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-top-opt350m"
disable_adapter = true

[model_layer_18.w1]
r = 0
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-top-opt350m"
disable_adapter = true

[model_layer_18.w2]
r = 0
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-top-opt350m"
disable_adapter = true

[model_layer_19.q_proj]
r = 24
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-top-opt350m"
disable_adapter = false

[model_layer_19.k_proj]
r = 0
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-top-opt350m"
disable_adapter = true

[model_layer_19.v_proj]
r = 24
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-top-opt350m"
disable_adapter = false

[model_layer_19.o_proj]
r = 0
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-top-opt350m"
disable_adapter = true

[model_layer_19.w1]
r = 0
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-top-opt350m"
disable_adapter = true

[model_layer_19.w2]
r = 0
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-top-opt350m"
disable_adapter = true

[model_layer_20.q_proj]
r = 24
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-top-opt350m"
disable_adapter = false

[model_layer_20.k_proj]
r = 0
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-top-opt350m"
disable_adapter = true

[model_layer_20.v_proj]
r = 24
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-top-opt350m"
disable_adapter = false

[model_layer_20.o_proj]
r = 0
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-top-opt350m"
disable_adapter = true

[model_layer_20.w1]
r = 0
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-top-opt350m"
disable_adapter = true

[model_layer_20.w2]
r = 0
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-top-opt350m"
disable_adapter = true

[model_layer_21.q_proj]
r = 24
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-top-opt350m"
disable_adapter = false

[model_layer_21.k_proj]
r = 0
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-top-opt350m"
disable_adapter = true

[model_layer_21.v_proj]
r = 24
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-top-opt350m"
disable_adapter = false

[model_layer_21.o_proj]
r = 0
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-top-opt350m"
disable_adapter = true

[model_layer_21.w1]
r = 0
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-top-opt350m"
disable_adapter = true

[model_layer_21.w2]
r = 0
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-top-opt350m"
disable_adapter = true

[model_layer_22.q_proj]
r = 24
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-top-opt350m"
disable_adapter = false

[model_layer_22.k_proj]
r = 0
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-top-opt350m"
disable_adapter = true

[model_layer_22.v_proj]
r = 24
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-top-opt350m"
disable_adapter = false

[model_layer_22.o_proj]
r = 0
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-top-opt350m"
disable_adapter = true

[model_layer_22.w1]
r = 0
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-top-opt350m"
disable_adapter = true

[model_layer_22.w2]
r = 0
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-top-opt350m"
disable_adapter = true

[model_layer_23.q_proj]
r = 24
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-top-opt350m"
disable_adapter = false

[model_layer_23.k_proj]
r = 0
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-top-opt350m"
disable_adapter = true

[model_layer_23.v_proj]
r = 24
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-top-opt350m"
disable_adapter = false

[model_layer_23.o_proj]
r = 0
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-top-opt350m"
disable_adapter = true

[model_layer_23.w1]
r = 0
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-top-opt350m"
disable_adapter = true

[model_layer_23.w2]
r = 0
lora_alpha = 16
lora_dropout = 0.0
adapter_name = "ags-layer-top-opt350m"
disable_adapter = true
