dataset_info: !!python/object:dataset.dataset_info_util.AgsDatasetInfo
  _entries: !!set
    available_splits: null
    causal_LM: null
    dataset_source: null
    name: null
    num_classes: null
    num_features: null
    seq2seqLM: null
    sequence_classification: null
  available_splits: !!python/tuple
  - !!python/object/apply:dataset.dataset_info_util.DatasetSplit
    - train
  - !!python/object/apply:dataset.dataset_info_util.DatasetSplit
    - validation
  - !!python/object/apply:dataset.dataset_info_util.DatasetSplit
    - pred
  causal_LM: false
  data_collator_cls: null
  dataset_source: !!python/object/apply:dataset.dataset_info_util.DatasetSource
  - hf_datasets
  name: sst2
  num_classes: 2
  num_features: null
  preprocess_one_split_for_all: true
  seq2seqLM: false
  sequence_classification: true
epochs: 1
eta_min: 0
learning_rate: 0.0001
lr_scheduler: none
optimizer: adamw
weight_decay: 0.01
