total_reallocation_number = 100

[layer_23]
q_proj = 21
v_proj = 18

[layer_22]
q_proj = 19
v_proj = 24

[layer_21]
q_proj = 19
v_proj = 26

[layer_20]
q_proj = 22
v_proj = 31

[layer_19]
q_proj = 24
v_proj = 26

[layer_18]
q_proj = 28
v_proj = 18

[layer_17]
q_proj = 27
v_proj = 23

[layer_16]
q_proj = 26
v_proj = 31

[layer_15]
q_proj = 22
v_proj = 21

[layer_14]
q_proj = 24
v_proj = 28

[layer_13]
q_proj = 21
v_proj = 24

[layer_12]
q_proj = 21
v_proj = 28

[layer_11]
q_proj = 26
v_proj = 20

[layer_10]
q_proj = 31
v_proj = 27

[layer_9]
q_proj = 24
v_proj = 21

[layer_8]
q_proj = 36
v_proj = 33

[layer_7]
q_proj = 16
v_proj = 32

[layer_6]
q_proj = 23
v_proj = 29

[layer_5]
q_proj = 28
v_proj = 21

[layer_4]
q_proj = 26
v_proj = 26

[layer_3]
q_proj = 23
v_proj = 25

[layer_2]
q_proj = 22
v_proj = 23

[layer_1]
q_proj = 31
v_proj = 24

[layer_0]
q_proj = 31
v_proj = 30
