total_reallocation_number = 20

[layer_0]
q_proj = 0
v_proj = 0
residual_1 = 0
residual_2 = 0
shortcut_sa = 0

[layer_1]
q_proj = 0
v_proj = 0
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_2]
q_proj = 0
v_proj = 0
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_3]
q_proj = 0
v_proj = 0
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_4]
q_proj = 0
v_proj = 20
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_5]
q_proj = 0
v_proj = 20
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_6]
q_proj = 0
v_proj = 20
residual_1 = 0
residual_2 = 0
shortcut_sa = 20
shortcut_ffn = 0

[layer_7]
q_proj = 0
v_proj = 20
residual_1 = 0
residual_2 = 0
shortcut_sa = 20
shortcut_ffn = 0

[layer_8]
q_proj = 0
v_proj = 20
residual_1 = 0
residual_2 = 0
shortcut_sa = 20
shortcut_ffn = 20

[layer_9]
q_proj = 0
v_proj = 20
residual_1 = 0
residual_2 = 0
shortcut_sa = 20
shortcut_ffn = 0

[layer_10]
q_proj = 0
v_proj = 20
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 20

[layer_11]
q_proj = 0
v_proj = 20
residual_1 = 20
residual_2 = 20
shortcut_sa = 20
shortcut_ffn = 0

[layer_12]
q_proj = 0
v_proj = 20
residual_1 = 20
residual_2 = 0
shortcut_sa = 20
shortcut_ffn = 1

[layer_13]
q_proj = 0
v_proj = 20
residual_1 = 0
residual_2 = 0
shortcut_sa = 20
shortcut_ffn = 0

[layer_14]
q_proj = 0
v_proj = 20
residual_1 = 0
residual_2 = 0
shortcut_sa = 20
shortcut_ffn = 0

[layer_15]
q_proj = 0
v_proj = 20
residual_1 = 0
residual_2 = 0
shortcut_sa = 20
shortcut_ffn = 20

[layer_16]
q_proj = 0
v_proj = 20
residual_1 = 20
residual_2 = 0
shortcut_sa = 20
shortcut_ffn = 0

[layer_17]
q_proj = 0
v_proj = 20
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_18]
q_proj = 0
v_proj = 20
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_19]
q_proj = 0
v_proj = 20
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_20]
q_proj = 0
v_proj = 20
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_21]
q_proj = 0
v_proj = 20
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_22]
q_proj = 0
v_proj = 0
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0

[layer_23]
q_proj = 0
v_proj = 19
residual_1 = 0
residual_2 = 0
shortcut_sa = 0
shortcut_ffn = 0
