total_reallocation_number = 20

[layer_23]
q_proj = 4
v_proj = 5

[layer_22]
q_proj = 4
v_proj = 3

[layer_21]
q_proj = 3
v_proj = 3

[layer_20]
q_proj = 4
v_proj = 2

[layer_19]
q_proj = 9
v_proj = 7

[layer_18]
q_proj = 5
v_proj = 4

[layer_17]
q_proj = 4
v_proj = 3

[layer_16]
q_proj = 9
v_proj = 6

[layer_15]
q_proj = 5
v_proj = 1

[layer_14]
q_proj = 10
v_proj = 4

[layer_13]
q_proj = 4
v_proj = 2

[layer_12]
q_proj = 4
v_proj = 4

[layer_11]
q_proj = 9
v_proj = 5

[layer_10]
q_proj = 7
v_proj = 14

[layer_9]
q_proj = 5
v_proj = 4

[layer_8]
q_proj = 6
v_proj = 3

[layer_7]
q_proj = 6
v_proj = 5

[layer_6]
q_proj = 6
v_proj = 2

[layer_5]
q_proj = 4
v_proj = 5

[layer_4]
q_proj = 6
v_proj = 6

[layer_3]
q_proj = 5
v_proj = 5

[layer_2]
q_proj = 4
v_proj = 5

[layer_1]
q_proj = 4
v_proj = 4

[layer_0]
q_proj = 4
v_proj = 7
